# 数据源配置
spring:
  redis:
    timeout: 1000
    host: 192.168.1.204
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://127.0.0.1:3306/pandown?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
      username: root
      password: A25
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 5
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
  security:
    basic:
      path: /swagger-ui.html
      enabled: true
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: UTF-8
    username: xxx@163.com
    password: xxx
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: input
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



snowflake:
  machine-id: 1
  data-center-id: 1

pandown:
  Account:
    cookies: "BAIDU_WISE_UID=wapp_1676293108995_690; PANWEB=1; PSTM=1677429102; ZFY=5E:BJorOCHA7Wi5smW4uldUw:AoNlZQUcQkL9Sb2RmVEE:C; BIDUPSID=56C0C0ED879D38BE155BE6D4F2C06331; BAIDUID=30434187CCBE170ED911242A3DEE58A8:FG=1; BAIDUID_BFESS=30434187CCBE170ED911242A3DEE58A8:FG=1; BDCLND=FjsaDdahS3MD8m2e1rB1Gh65rc9cBQL%2BXMs72C1b%2BqI%3D; csrfToken=IYF9E2PTNdgqsCT7Ti9XNIKV; newlogin=1; BDUSS=l-VWV5YjRhd1BkR1BmQk1kR21LME9HVGtUN2RQWDUxazNoQXVpQ0dSOE1GbmhrSVFBQUFBJCQAAAAAAAAAAAEAAAD-Q1grYTIyNjkyNzZlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyJUGQMiVBkTj; BDUSS_BFESS=l-VWV5YjRhd1BkR1BmQk1kR21LME9HVGtUN2RQWDUxazNoQXVpQ0dSOE1GbmhrSVFBQUFBJCQAAAAAAAAAAAEAAAD-Q1grYTIyNjkyNzZlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyJUGQMiVBkTj; STOKEN=30621ea24dd17717b4ccea5483afe0b7cf0a97b70404c449c0cea6497687ecfb; ndut_fmt=6AA7CF2196CC37D632A87EF6AB15A124F5D2010FDB5C70425E00E59F789C8BB9; ab_sr=1.0.1_MmEyODQ0MjI0OTEyY2E2ZjU5YjgxYjY5OGY5ZGFlYTI4YmM5OGMyYjc2MjBhMGY1ZDMwYmQwYzdmYTZhOTQ0OTQ5YjcxYjYyNDQ5Y2E5ZDhkOTkyMzBmYTRiYWQ5NWMyZDEwOTNiN2I4MTVkYzlhMjBlZTkyYjdhOGU0Zjk5N2VkMThmYjdjZmU5Y2ZkM2RhMjJiOGYxZmRlMWI3NmM2MzBmODM2ZDAzOTUwOGNiM2UzNGIyN2EyN2E4OTA2MWU4; PANPSC=10660478181080867701%3AeDVC44VMlkuwpVgviK7pHVcS2d9ns3O5WSpAOtiYnuooK5JNovHgnDJ3TFL5%2B7J8K9sKmG0jScziRClWYPNr2cPKVjvvBMbo2uXu4bOTdjc2jyb7JodIivKBB5%2BWSCTpbaC532AuNi3w0iRW66wpcQelhSA6FDy8slZuWNt1qytZJEFwtmF4sQzCIHAAYipkAsGNr4paWK3EGlSCrabBxOtuQFScyIV%2FkrFWWqsgPEw%3D"
  JWT:
    rsaPublicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALlqbfk6hyvTnfZWsIBHfQfHRyDCNGBHZAYvoLod2eZLcK6L/R+8cgpTsgx16KjY4Uv3EAPwtKlyoVPXgBu1AMcCAwEAAQ==
    rsaPrivateKey: MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAuWpt+TqHK9Od9lawgEd9B8dHIMI0YEdkBi+guh3Z5ktwrov9H7xyClOyDHXoqNjhS/cQA/C0qXKhU9eAG7UAxwIDAQABAkEArTGWMkSSeMS9+5m0Ws7sInTpotblF73317Nrfg5eOLdNzuMfRJbXU/mm8rCddsonegfHV+mFQR4XxmlqW2X4EQIhAON8mZSKY3PqTiyvtGltbIeDAzeu/gi+z/1kFgBKXSC/AiEA0KfkVxRTIDqSeo0DEVPOFE6ZWkAgiY5LZ0KSg1bymfkCIEXPpxH+piaccQElqqfv/K5ZdlNQUIU+iXWpkVble07hAiA9QLw4j//jGy67CUBYStjZf0VniCHFH9+k3ZczNUgcyQIhAOIeGwTy19+7P84mgoiOIQc7xhc9dlJcdxmb4kQ6hYcN
    expireTime: 30
  downloadApi:
    getFileList:
      url: https://pan.baidu.com/share/wxlist
    getSignAndTime:
      url: https://pan.baidu.com/share/tplconfig
    getDlink:
      url: https://pan.baidu.com/api/sharedownload
    getAccountState:
      url: https://pan.baidu.com/api/gettemplatevariable

server:
  port: 8080

springfox:
  documentation:
    swagger-ui:
      enabled: true
